arduino/arduino-lint

.github/workflows/test-install.yml
In addition to being fairly complex and convoluted, the install script has a fragile reliance on the release page HTML
having a specific format. It also relies on the file being available at a specific path on the Arduino download server,
which is subject to change.
=> [skip changelog] Add workflow to test install script

.github/workflows/release.yml
The new `create-changelog` version fixes a bug that caused the whole `git log` to be used as changelog.
=> [skip changelog] Update create-changelog action in release workflow

internal/rule/rulefunction/rulefunction.go
Missing parentheses resulted in the regular expression matching files that are not recognized as a readme by GitHub.
=> Correct readme filename regular expression

internal/project/project.go, internal/project/project_test.go
The documentation of the `--project-type` flag promises that subprojects will also be discovered:
```
--project-type string      Only lint projects of the specified type and their subprojects. Can be {sketch|library|platform|all}. (default "all")
```
Under a specific combination of configurations a bug caused subprojects to not be discovered:
- `--project-type` flag set to specific project type.
- `--recursive` flag not used.
- `PROJECT_PATH` is a folder (rather than file).
So, for example, given this project structure:
```
FooLibrary
|-- examples
|   `-- FooExample
|       `-- FooExample.ino
|-- src
|   `-- FooLibrary.h
`-- library.properties
```
The following command only linted the library, and not the FooExample sketch:
```
arduino-lint --project-type library FooLibrary
```
Under any …
=> Always discover subprojects

.github/workflows/check-certificates.yml
At the time the workflow was written the authors of the `rtCamp/action-slack-notify` GitHub Action did not provide a major version ref. This meant that it was necessary to pin the action to a specific version.
Since then, a few new patch releases have been made, meaning an outdated version of the action was in use as a consequence of the pinning. 
The action now offers [a `v2` major ref](https://github.com/rtCamp/action-slack-notify/releases/tag/v2). Use of this ref will cause the workflow to benefit from ongoing development to the action up until such time as a new major release is made, at which time we would need to evaluate whether any changes to the workflow are required by the breaking change that triggered the major release before updating the major ref (e.g., `v3`).
One of the …
=> Use major version ref of action in workflow

docs/index.md, go.mod, go.sum, internal/configuration/configuration.go, internal/configuration/configuration_test.go, internal/configuration/defaults.go, internal/configuration/rulemode/rulemode.go, internal/configuration/rulemode/rulemode_test.go, internal/configuration/rulemode/type_string.go, internal/project/projectdata/library.go, internal/rule/ruleconfiguration/ruleconfiguration.go, test/test_all.py
Some of Arduino Lint's rules are based on the data in [the published Arduino Library Manager index](http://downloads.arduino.cc/libraries/library_index.json). These allow library maintainers to check compliance with the Library Manager submission or update requirements.
Work is now in progress to use Arduino Lint to validate library releases during the generation of the index. In this usage, data from the published index is not relevant, meaning the results from those rules are inaccurate and so downloading the index for the sake of them is a waste. So another configuration mode is needed to to allow the index-based rules to be disabled.
Since this mode is of no use to normal users of Arduino Lint, it is enabled via an environment variable so that no unnecessary complexity is added to the …
=> Add a Library Manager configuration for linting while indexing releases

go.sum, internal/rule/rulefunction/library.go
Rules `LP045` and `LP046` utilize a lists of standardized architecture names. In the recent [2.0.0 release of the Arduino Mbed
OS Boards platform](https://github.com/arduino/ArduinoCore-mbed/releases/tag/2.0.0), the `mbed` architecture was split into four variants:
- `mbed_edge` (Arduino Edge Control)
- `mbed_nano` (Arduino Nano 33 BLE, Arduino RP2040 Connect)
- `mbed_portenta` (Arduino Portenta H7)
- `mbed_rp2040` (Raspberry Pi Pico and other 3rd party RP2040 boards)
So the architecture lists used in the rules should be updated accordingly.
=> Add new mbed architecture variants to rules

internal/rule/rulefunction/library.go
The alternative development framework alias for the RP2040's architecture is ["raspberrypi"](https://platformio.org/platforms/raspberrypi).
=> Expand rule LP045 to cover RP2040 architectures

internal/rule/ruleconfiguration/ruleconfiguration.go, test/test_all.py, test/testdata/library-manager/ARDUINO_LINT_LIBRARY_MANAGER_INDEXING/Servo/library.properties
This rule checks for the presence of the library's library.properties `depends` items in the library index. Since the
library index is not available when in `ARDUINO_LINT_LIBRARY_MANAGER_INDEXING` mode, this rule can not run.
Before this change, attempting to lint a library with a library.properties `depends` field when in `ARDUINO_LINT_LIBRARY_MANAGER_INDEXING` mode resulted in a panic:
```
panic: interface conversion: interface {} is nil, not []interface {}
goroutine 1 [running]:
github.com/arduino/arduino-lint/internal/rule/rulefunction.nameInLibraryManagerIndex(0xc000160206, 0x19, 0xddae1d)
/home/build/internal/rule/rulefunction/library.go:1447 +0x1be
github.com/arduino/arduino-lint/internal/rule/rulefunction.LibraryPropertiesDependsFieldNotInIndex(0xdcd21e, 0x18, 0xc0005a1890) …
```
=> Disable LP048 for ARDUINO_LINT_LIBRARY_MANAGER_INDEXING mode

.github/workflows/check-formatting.yml, .github/workflows/check-links.yml, .github/workflows/lint-code.yml, .github/workflows/lint-config.yml, .github/workflows/lint-documentation.yml, .github/workflows/lint-python.yml, .github/workflows/lint-shell.yml, .github/workflows/nightly.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml, .github/workflows/spell-check.yml, .github/workflows/test.yml, .github/workflows/validate-docs.yml
The GitHub Actions action for installing [Task](https://taskfile.dev/#/) has graduated from its original home in [the experimental `arduino/action`repository](https://github.com/arduino/actions) with a move to a dedicated permanent repository at [`arduino/setup-task`](https://github.com/arduino/setup-task).
A [1.0.0 release](https://github.com/arduino/setup-task/releases/tag/v1.0.0) has been made and [a `v1` ref](https://github.com/arduino/setup-task/tree/v1) that will track all releases in the major version 1 series. Use of the action's major version ref will cause the workflow to benefit from ongoing development to the action at each [patch or minor release](https://semver.org/) up until such time as a new major release is made. At this time the user will be given the opportunity to …
=> Use new arduino/setup-task action name in CI/CD workflows

internal/project/project.go, internal/project/project_test.go
Specific combinations of symlinks can cause infinite recursion loops during project discovery. This can be avoided by
limiting the depth of symlink follows to a reasonable number.
This was implemented in https://github.com/arduino/arduino-lint/commit/ef717d23021545ad74496aa27e0b37ce1ae0eeb1 to make the project discovery code gracefully avoid perpetual recursion in this situation. Unfortunately, it turned out that the project data collection phase that comes after project discovery also suffers from the same problem. Fixing that is more difficult since the incompatible code is in Arduino CLI. So for now the provisional fix is to panic during the project discovery phase, which will at least avoid the far worse behavior of a permanent hang.
=> Avoid hang when linting projects with symlink loops

.github/workflows/test.yml
Providing pre-built binaries for every pull request or commit that changes relevant files enables any interested party to
participate in the review or beta testing process without imposing the requirement to set up the build toolchain on their
local machine.
This will also avoid any chance of differences between the tester's environment and the release system environment
introducing spurious results.
=> Generate test build artifacts

etc/schemas/arduino-library-properties-definitions-schema.json, etc/schemas/arduino-package-index-definitions-schema.json, etc/schemas/arduino-package-index-permissive-schema.json, etc/schemas/arduino-package-index-schema.json, etc/schemas/arduino-package-index-strict-schema.json, etc/schemas/general-definitions-schema.json, go.mod, internal/project/library/libraryproperties/librarypropertiesschemas_test.go, internal/project/packageindex/packageindex.go, internal/project/packageindex/packageindex_test.go, internal/project/packageindex/packageindexschemas_test.go, internal/project/packageindex/testdata/package_valid_index.json, internal/rule/schema/parsevalidationresult.go, internal/rule/schema/schema_test.go, internal/rule/schema/schemadata/bindata.go, internal/rule/schema/testdata/bindata.go, internal/rule/schema/testdata/input/referenced-schema-2.json, internal/rule/schema/testdata/input/valid-schema-with-references.json
This schema defines the data structure of the [Arduino package index](https://arduino.github.io/arduino-cli/dev/package_index_json-specification) at three [compliance ](https://arduino.github.io/arduino-lint/dev/#compliance-setting)levels:
- permissive: the minimum accepted format. This allows for a gradual deprecation following specification changes.
- specification: the format as defined in [the official specification](https://arduino.github.io/arduino-cli/dev/package_index_json-specification)
- strict: best practices
Helper functions for reading package indexes and validating them against the schema are added, at this point for use in
the tests, but also for the schema-based rules to come.
=> Add JSON schema for package index

internal/rule/rulefunction/library.go, internal/rule/rulefunction/library_test.go
From the `http.Get()` documentation:
> Caller should close resp.Body when done reading from it.
This was not done previously. Since the body is not needed, `http.Head()` is more appropriate for this application and it
does not impose the requirement to add additional code to clean up.
=> Use most appropriate function for checking URL

internal/project/packageindex/packageindexschemas_test.go, internal/rule/schema/parsevalidationresult.go, internal/rule/schema/schema_test.go
When used with [the "properties" data format](https://pkg.go.dev/github.com/arduino/go-properties-orderedmap#pkg-overview), and most especially with the flat format of the [library.properties](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format) file that was an initial focus of the project's development, [JSON pointers](https://datatracker.ietf.org/doc/html/rfc6901) are not a terribly intuitive way to refer to a data path.
In this context, it seemed sensible to pre-fill the root prefix on the instance pointer argument of the JSON schema validation result parsing functions. However, now that those functions are being used with the JSON formatted [package index](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/) data …
=> Allow full JSON pointers in schema validation result parsing functions

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go, internal/project/projectdata/testdata/packageindexes/valid-package-index/package_foo_index.json
Data checking rules for package indexes need to iterate over its object-level components. To facilitate this, slices of
such objects accompanied by the necessary metadata are generated as package index project data.
=> Provide object-level project index data to rules

internal/project/projectdata/packageindex_test.go, internal/project/projectdata/testdata/packageindexes/valid-package-index/package_foo_index.json, internal/rule/rulefunction/packageindex_test.go, internal/rule/rulefunction/testdata/packageindexes/packages-help-online-dead/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/packages-platforms-help-online-dead/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/packages-platforms-url-dead/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/packages-tools-systems-url-dead/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/packages-websiteurl-dead/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/packages-websiteurl-invalid/package_foo_index.json, internal/rule/rulefunction/testdata/packageindexes/valid-package-index/package_foo_index.json, test/testdata/project-type/PackageIndex/package_valid_index.json
- Use more appropriate packager name in test data package indexes
- Add test messages to all package index project data tests
- Correct order of arguments in test equality assertions
=> Various minor improvements to unit tests for package index projects

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go, internal/project/projectdata/testdata/packageindexes/missing-ids/package_foo_index.json
In order to provide rule results, it's necessary to identify even completely invalid package index components. The
previous behavior of skipping these components did not allow that.
=> Add slice entries to projectdata for all package index components

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go, internal/project/projectdata/testdata/packageindexes/empty-ids/package_foo_index.json
In cases where the data used to assemble the standard ID used to refer to a package component is undefined, the JSON
pointer is used.
Previously, when the data is defined, but empty, the standard ID format was used. But this will not be very meaningful.
In this case, the JSON pointer will serve as a more useful ID.
=> Use JSON pointer as package component ID when standard ID component empty

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go
This allows the package index to be validated against its JSON schemas only once per project, with those results shared
between all the schema-based rules.
=> Provide schema validation results in package index project data

internal/rule/rulefunction/packageindex.go
=> Correct typos in package index rule function doc comments

etc/schemas/arduino-package-index-definitions-schema.json, internal/project/packageindex/packageindexschemas_test.go, internal/rule/schema/schemadata/bindata.go
The `packages[].platforms[].size` and `packages[].tools[].systems[].size` properties are string representations of
integers, and thus must consist solely of the characters 0-9. The previous regular expression for a valid size value only
required that a number be found somewhere in the string.
=> Correct package index schema's regex for size property

internal/project/projectdata/packageindex.go
The previous inflexible approach to defining the format of the identifiers used for package index components in rule
messages will not allow for identifying platform tool dependencies. A template approach will support any ID format.
=> Use a template to define package index component ID format

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go, internal/project/projectdata/testdata/packageindexes/empty-ids/package_foo_index.json, internal/project/projectdata/testdata/packageindexes/missing-ids/package_foo_index.json, internal/project/projectdata/testdata/packageindexes/valid-package-index/package_foo_index.json
Data checking rules for package indexes need to iterate over its object-level components. To facilitate this, slices of
such objects accompanied by the necessary metadata are generated as package index project data.
This was already done for packages, platforms, boards, and tools, but not for tools dependencies.
=> Provide object-level `packages[].platforms[].toolsDependencies[]` package index data to rules

docs/CONTRIBUTING.md
The raw release changelog is generated from the commit messages. The `arduino/create-changelog` action is configured to
omit any commit message that is prefixed with "[skip changelog]".
After extensive use of this approach in the Arduino CLI repository, my conclusion is that it provides a miniscule time
savings for the release manager at the cost of massive pollution of the valuable commit history and a significantly less
contributor friendly repository. For this reason, I have never employed this practice in my work on Arduino Lint and I do
not want contributors to do so either.
=> Rescind policy that commits should start with "[skip changelog]"

internal/rule/rulefunction/library.go, internal/rule/rulefunction/library_test.go
The use of [`FilterOutDirs()`](https://pkg.go.dev/github.com/arduino/go-paths-helper#PathList.FilterOutDirs) on the path list removed symlinks with folder targets, causing rule LS005 to only detect symlinks with file targets. But all types of symlinks are prohibited so this resulted in false negatives.
As reported at https://github.com/arduino/arduino-lint/pull/56#issuecomment-880569913
=> Make symlink prohibition rule catch links with folder target

go.mod, go.sum, internal/result/result.go, internal/result/result_test.go
Previously, the output text for the rule results had no formatting to speak of. It was simply a single, often long, line of text. Wrapping of this text was at the mercy of whatever displayed it. When there were multiple rule results in the output it melded into a wall of dense text.
The readability is improved by two formatting changes:
- Format the rule level (e.g., ERROR, WARNING) text and the rule message text into separate columns
- Wrap the rule message text, maintaining the column alignment after line breaks
This is accomplished by using [`github.com/olekukonko/tablewriter`](https://pkg.go.dev/github.com/olekukonko/tablewriter) to put the result output for each rule is made into a single row, borderless table.
Example output from before this change:
```
ERROR: Library name Servo is …
```
=> Format output text for rule results to improve readability

internal/project/projectdata/packageindex.go, internal/project/projectdata/packageindex_test.go, internal/rule/rulefunction/packageindex_test.go
Since package index data occurs in arrays, the rules must indicate to the user the specific element(s) in violation. In the case of standard components (e.g. platform), the form of the IDs is well established (e.g., `arduino:avr@1.8.3`). However, that I know of, there is no standard form for unequivocally identifying a package index data subcomponent (e.g., a tool dependency of a specific platform release).
I arbitrarily chose a dash to combine the IDs of the two components (e.g., `arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 - x86_64-linux-gnu`). I received feedback that this was not very clear, with a suggestion to use ">>" instead of the "-" (e.g., `arduino:avr-gcc@7.3.0-atmel3.6.1-arduino7 >> x86_64-linux-gnu`).
=> Use ">>" in place of "-" between package index ID components

.github/workflows/check-certificates.yml, README.md
We have assembled a collection of reusable GitHub Actions workflows:
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made to the "template" workflow, and these are introduced via this pull request.
---
This changes the name of the repository secret that contains the Slack webhook and I have already added the new secret.
=> Sync "Check Certificates" CI workflow with template

.ecrc, .github/workflows/check-general-formatting-task.yml, README.md, Taskfile.yml
On every push, pull request, and periodically, use [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) check whether the repository's files are formatted according to [`.editorconfig`](https://editorconfig.org/).
=> Add CI workflow to check general file formatting

docs/installation.md, etc/install.sh
We have assembled a collection of reusable project assets:
These assets will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made there to the installation script and documentation, and these are introduced via this pull request.
=> Sync installation assets from template

.github/workflows/check-formatting.yml, .github/workflows/check-prettier-formatting-task.yml, README.md, Taskfile.yml, docs/css/version-select.css, docs/js/version-select.js
We have assembled a collection of reusable GitHub Actions workflows:
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made to the "template" workflow, and these are introduced via this pull request.
=> Sync Prettier formatting check CI workflow with template

.github/workflows/check-workflows-task.yml, .github/workflows/lint-config.yml, README.md, Taskfile.yml
We have assembled a collection of reusable GitHub Actions workflows:
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, and those are introduced to this repository via this pull request.
=> Sync GitHub Actions workflow validation CI workflow with template

.github/workflows/check-license.yml, .github/workflows/lint-documentation.yml, Taskfile.yml
We have assembled a collection of reusable GitHub Actions workflows:
These workflows will be used in the repositories of all Arduino tooling projects.
Some minor improvements and standardizations have been made in the upstream "template" workflow, and those are introduced to this repository via this pull request.
=> Sync license check CI workflow with template

.github/workflows/check-go-task.yml
The `check-config` job of the "Check Go" workflow runs a check to see whether there were any missed updates to the
`go.mod` and `go.sum` files. Previously, this was only done for the main module. But there is an additional module for
generating the website's command reference content the update of which might easily be overlooked. The CI check was not
applied to this module, which could allow its metadata to get out of date.
The use of a job matrix allows the workflow to easily accomodate the future addition of more modules to the repository by
simply adding their path to the matrix array.
=> Run Go module configuration sync check also on docsgen module

docs/CONTRIBUTING.md
The Python script used by the website publishing system was moved during the sync to the "template" version but the link to it from `CONTRIBUTING.md` was not updated accordingly.
The reworking of the system that broke the link also removed the documentation content from that file. That content has been moved to the documentation for the template system. Since this content is for maintainers, and is not of interest to the average contributor, I think it is find to maintain that content in a single place in the assets repository, and link to it there.
=> Replace broken website publishing script link

.github/dependabot.yml
Dependabot will periodically check the versions of all the project's GitHub Actions, Go, and Python dependencies If any are found to be outdated, it will submit a pull request to update them.
=> Use Dependabot for dependency updates

poetry.lock, pyproject.toml
These are the dependency versions used by the versioned MkDocs website template, but I forgot to update them when I synced everything else (https://github.com/arduino/arduino-lint/pull/225).
Supersedes https://github.com/arduino/arduino-lint/pull/233
Supersedes https://github.com/arduino/arduino-lint/pull/234
=> Bump website versioning dependencies

.github/workflows/check-code-generation-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/spell-check-task.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml
Placement of this information at the top of the file, where it is easy to find and edit, facilitates updates to the
workflows as the tool version used for project development are bumped periodically.
This is an established convention in the "template" workflows, but I missed some applications of it. I think it's most
effective when done consistently throughout the workflows.
=> Use workflow variables for tool versions in all workflows

.github/workflows/test-go-task.yml
The `codecov/codecov-action` action is used in the unit test runner workflow to upload code coverage data to codecov. The workflow is configured to use the latest release within the specified major version series. It is necessary to manually update the workflow any time a new major version series of an action begins, in which case a review is necessary to determine whether the workflow is affected by the breaking changes that required the major bump.
The action is now in its 2.x version series. The cause of the major bump was the [removal of some of the action's inputs](https://github.com/codecov/codecov-action/releases/tag/v2.0.0). I reviewed the changes and found that none of the inputs used in the workflow are affected so it is possible to update without any other changes to the …
=> Bump `codecov/codecov-action` workflow dependency to v2

docsgen/go.mod, docsgen/go.sum, go.mod, go.sum
This indirect dependency had a force push that changed the checksum of its v1.0.0 tag 
(https://github.com/oleiade/reflections/issues/14). This causes Dependabot to fail, meaning it won't provide any notifications of dependency updates (nor is Dependabot so kind as to provide a notification of such failures):
https://github.com/arduino/arduino-lint/network/updates/180623112
> Dependabot can't resolve your Go dependency files
Dependabot failed to update your dependencies because there was an error resolving your Go dependency files.
Dependabot encountered the following error:
verifying github.com/oleiade/reflections@v1.0.0/go.mod: checksum mismatch
There has been a new release of `github.com/oleiade/reflections` and this is slowly working its way up Arduino Lint's supply chain, but it's …
=> Replace problematic release of `github.com/oleiade/reflections` dependency

.github/workflows/check-code-generation-task.yml, .github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/release-go-task.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml, .github/workflows/test-install.yml
These are the naming conventions established in [the standardized template workflows](https://github.com/arduino/tooling-project-assets/tree/main/workflow-templates).
=> Use standardized workflow/job/step names in workflows

.github/workflows/publish-go-tester-task.yml, Taskfile.yml, gon.config.hcl, tests/test_all.py
Some additional changes missed on the first pass (https://github.com/arduino/arduino-lint/pull/222), which are required for a full sync with [the standardized "template" project build assets](https://github.com/arduino/tooling-project-assets/tree/main/workflow-templates).
=> Finish sync of build infrastructure with "template" assets

Taskfile.yml, docs/CONTRIBUTING.md
Some housekeeping and streamlining of the [Task](https://taskfile.dev/#/) configuration file that provides common development operations for this project.
=> Clean up taskfile

.github/workflows/test-go-task.yml
The "Test Go" workflow uploads code coverage data to Codecov. There will occasionally be spurious upload failures caused by transient network outages. These will typically succeed after the workflow is re-run, but the option to re-run is not offered when the workflow run passes.
Because it's important that the data be complete, [the `codecov/codecov-action` action](https://github.com/codecov/codecov-action) is configured to fail the workflow run if the upload does not succeed. However, the upload will never be able to succeed for workflow runs in a fork where the owner has not set up Codecov. For this reason, [the `fail_ci_if_error` input](https://github.com/codecov/codecov-action#arguments) setting is made conditional upon [the repository …
=> Don't require Codecov upload success for test run in fork

.github/workflows/check-mkdocs-task.yml
Go 1.16 is now used for all development of this project (https://github.com/arduino/arduino-lint/pull/222/commits/86692a21368a93353e190ef4ada29640338b8baf). This is the last remaining component of the project infrastructure left specifiying Go 1.14.
=> Use standard version of Go in "Check Website" workflow

.github/workflows/check-code-generation-task.yml, .github/workflows/check-go-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml
The [trunk-based development](https://trunkbaseddevelopment.com/) strategy is used by this project. The release branch may contain a subset of the history of the default branch.
The status of the GitHub Actions workflows should be evaluated before making a release. However, this is not so simple as checking the status of the commit at the tip of the release branch. The reason is that, for the sake of efficiency, the [workflows are configured](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) to run only when the processes are relevant to the trigger event (e.g., no need to run unit tests for a change to the readme).
In the case of the default branch, you can simply [set the workflow runs filter to that …
=> Run relevant workflows on release branch creation

internal/project/general/general.go, internal/project/general/general_test.go
The Arduino project configuration fields have an odd usage of the `properties.Map` format. Dots may sometimes indicate nested keys, but in other cases they are merely a character in the key string. Previously, the utility function used to recursively map to a configurable depth was not correctly handling this situation due to using the same code both for the recursive mapping to subkeys as well as for the flat mapping at the final depth. The fix for the bug also makes the function more efficient by avoiding calling `SubTree()` when it's already known there is no subtree.
=> Fix properties mapping utility function handling of overlapping keys

internal/rule/schema/schema.go
The `err` return value of `*jsonschema.Schema.ValidateInterface()` is used to pass the schema validation failure result.
That error type is given special treatment by Arduino Lint because it occurs under normal circumstances when a rule
violation occurs, and must be interpreted by the rule functions, or even ignored, depending on the tool configuration.
The `err` return value of `*jsonschema.Schema.ValidateInterface()` is also used to return errors that indicate some
unexpected problem has occurred separate from a schema validation failure. Previously, these other error types were
ignored and the validation treated as if it had passed, even though it likely never even ran.
Since Arduino Lint controls both the instance and schema data, such these true errors returned by the validation …
=> Panic on unexpected schema validation error

.codespellrc, .ecrc, .editorconfig, .github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/release-go-task.yml, Taskfile.yml
We have assembled a collection of reusable project assets:
These are used in the repositories of all Arduino tooling projects.
Some minor fixes, improvements, and standardizations have been made in the upstream "template" assets, and those are introduced to this repository via this pull request.
=> Sync project assets from the standardized "template" versions

docs/installation.md
A defect fix and multiple improvements have been made to the upstream "template" installation documentation which this project's installation docs are based on:
https://github.com/arduino/tooling-project-assets/blob/main/other/installation-script/installation.md
This PR pulls those changes into this repo's installation documentation.
=> Sync install docs from "template"

internal/project/projectdata/packageindex_test.go
In preparation for linting a project, Arduino Lint collects information that may be needed by multiple rules, referred to as "project data".
For [package index](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/) projects, this data includes the contents of the `packages[].platforms[].discoveryDependencies[]` field, stored in a slice along with identifiers.
At the time the code was added for collecting that project data, new assertions were added to the unit test tables to cover it, but the test table handling code was not updated, meaning the assertions were never tested.
This PR adds that missing test table handling code and also fixes some errors in the assertions that were revealed by testing them.
=> Fix errors in package index project data unit tests for `discoveryDependencies`

.github/dependabot.yml
The repository contains three Go modules:
- `github.com/arduino/arduino-lint` - in the repository root
- `github.com/arduino/arduino-lint/docsgen` -  in `docsgen/`
- `github.com/arduino/arduino-lint/ruledocsgen` -  in `ruledocsgen/`
Dependabot has been configured to submit PRs for updates of the first two modules, but the Dependabot configuration was
not updated at the time the `github.com/arduino/arduino-lint/ruledocsgen` module was added, so it is not receiving that
important service.
=> Use Dependabot to maintain dependencies of the ruledocsgen module

etc/install.sh
The installation script checks for an existing installation in the `PATH` in order to provide appropriate advice to the user about adding the installation to their their `PATH` environment variable.
This check is done using `command -v`. It turns out that the exit status is shell dependent in the event the command is not found, so that it might be either `1` or `127` depending on the user's system. The script previously assumed that the exit status would be `1` when the command was not found in `PATH`, which resulted in spurious advice under these conditions:
https://github.com/arduino/arduino-lint/runs/4577911186?check_suite_focus=true#step:3:11
```
An existing arduino-lint was found at . Please prepend "/home/runner/work/arduino-lint/arduino-lint/bin" to your $PATH or remove the …
```
=> Fix install script's check for previous installation

Taskfile.yml
Go commands used during the development of this project may take a list of packages as argument. Generally, we will want to run the command on most of the packages of the targeted module, excluding selected packages which are not of interest (e.g., [the automatically generated `github.com/arduino/arduino-lint/internal/rule/schema/schemadata` package](https://github.com/arduino/arduino-lint/tree/4f0fa8b6a3a70d1f293fef732d54ff65e638ec23/internal/rule/schema/schemadata)).
The list of packages is generated using the `go list` command.
Previously, the list was defined via [a "dynamic" taskfile variable](https://taskfile.dev/#/usage?id=dynamic-variables). The benefit to that approach was that the `go list` command ran only once per execution of [`task`](https://taskfile.dev/#/). However, there …
=> Avoid unnecessary `go list` command execution when running tasks

etc/install.sh
An installation script contained in this repository provides convenient installation of Arduino CLI:
https://arduino.github.io/arduino-lint/dev/installation/#use-the-install-script
Some defects are present in the script's handling of lack of a build for a specific host architecture, which manifested when users with Apple M1 systems attempted to use it:
- https://github.com/arduino/arduino-lint/issues/348
- https://github.com/arduino/arduino-cli/issues/1714
The script is hosted and maintained in [a separate repository](https://github.com/arduino/tooling-project-assets) as part of a collection of reusable tooling project assets.
The defects in the script were fixed, and some general improvements made to the related code, in that repository:
- Remove broken frivolous function from install …
=> Fix installation script bugs affecting Apple M1 users

.markdown-link-check.json
The link check job of the "Check Markdown" workflow has had frequent intermittent spurious failures recently, caused by links under the `docs.github.com` domain returning [403 HTTP status](https://en.wikipedia.org/wiki/HTTP_403).
Others experiencing the same problem reported that they were able to work around the problem by providing a custom [`Accept-Encoding` HTTP request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding). Although I was not able to find any explanation of why, it does appear to resolve the problem.
Since the problem seems to be permanent and the only other workarounds I have identified are unappealing (considering links returning 403 statuses alive, or ignoring all `docs.github.com` links), I think it is worth a try.
=> Configure link check to use `Accept-Encoding` header for docs.github.com links

docs/installation.md
The nightly build download link for macOS ARM 64-bit in the installation instructions template was missing the `nightly` subfolder these files are uploaded to.
The previous URL receives an HTTP 404 code response:
https://downloads.arduino.cc/arduino-lint/arduino-lint_nightly-latest_macOS_ARM64.tar.gz
The correct URL with the subfolder:
https://downloads.arduino.cc/arduino-lint/nightly/arduino-lint_nightly-latest_macOS_ARM64.tar.gz
=> Correct macOS ARM 64-bit nightly download link in installation docs

.github/workflows/check-certificates.yml
The "Check Certificates" GitHub Actions workflow uses [**OpenSSL**](https://www.openssl.org/) to check for problems with the project's signing certificates.
Certificates exported to [PKS #12](https://en.wikipedia.org/wiki/PKCS_12) archive files using older tools may have been encrypted using the ["RC2-40-CBC" algorithm](https://en.wikipedia.org/wiki/RC2).
Due to the availability of more secure modern alternatives, [default support for "RC2-40-CBC" encryption was dropped in **OpenSSL** 3.x](https://www.openssl.org/docs/man3.0/man7/migration_guide.html#PKCS-12-API-updates).
This project's macOS signing certificate uses "RC2-40-CBC" encryption.
The "Check Certificates" GitHub Actions workflow runs on [the `ubuntu-latest` runner](https://docs.github.com/en/actions/using-workflows/workflow-synt …
=> Restore certificate check compatibility w/ RC2-40-CBC encrypted PKS#12

.github/workflows/check-go-dependencies-task.yml
The [**licensed**](https://github.com/github/licensed) tool is used to check for the project's compatibility with the licensing of its dependencies.
This tool is installed by the "Check Go Dependencies" GitHub Actions [workflow]([GitHub Actions workflow](https://docs.github.com/actions/using-workflows/about-workflows)) using [the `jonabc/setup-licensed` GitHub Actions action](https://github.com/jonabc/setup-licensed). This action attempts the installation according to the following procedure:
1. Install [the Ruby gem](https://rubygems.org/gems/licensed).
1. If gem installation fails, install the [release](https://github.com/github/licensed/releases/latest) asset from the `github/licensed` repo.
Spurious failures of the "Check Go Dependencies" workflow runs are occurring due to hitting …
=> Configure "Check Go Dependencies" workflow to avoid failure of licensed installation

internal/rule/rulefunction/rulefunction.go, internal/rule/rulefunction/sketch_test.go, internal/rule/rulefunction/testdata/sketches/AllowedCharactersInFilenames/AllowedCharactersInFilenames.ino
The Arduino Sketch Specification defines the allowed format of sketch folder names and sketch code filenames. Arduino Lint's rule SS002 checks compliance with the specification.
The Arduino Sketch Specification is being changed to allow a leading underscore in sketch folder names and sketch code filenames:
https://github.com/arduino/arduino-cli/pull/2105
The Arduino Lint rule code must be updated accordingly.
=> Allow leading underscore in sketch filenames

etc/schemas/arduino-library-properties-definitions-schema.json, internal/rule/ruleconfiguration/ruleconfiguration.go, internal/rule/rulefunction/library_test.go, internal/rule/rulefunction/testdata/libraries/NameIsBiggerThanRecommendedLength/library.properties, internal/rule/schema/schemadata/bindata.go
As reported in https://github.com/arduino/arduino-lint/issues/508 , the current linter rules limit the max number of characters for a library name to 16. 
https://github.com/arduino/arduino-lint/blob/c2c82d654e1cf2888112cfc83e3417342b163227/etc/schemas/arduino-library-properties-definitions-schema.json#L94
https://github.com/arduino/arduino-lint/blob/c2c82d654e1cf2888112cfc83e3417342b163227/internal/rule/ruleconfiguration/ruleconfiguration.go#L427
As noted by @aentinger , since Arduino libraries start with `Arduino_`, this leaves only 8 characters to describe the library according to the linter rules. **This PR increases the maximum length of a library name to ~64~ 32 characters**. For official libraries with the leading `Arduino_`, this provides ~56~ 24 characters which should be …
=> [AE-26] Increase Library name length from 16 to 32

.github/workflows/check-markdown-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
The project documentation is published on [a companion website](https://arduino.github.io/arduino-lint/dev/). A GitHub Actions workflow is used to automatically update the website whenever any relevant file is changed in the repository. This website includes content generated from the project's Go code.
Previously, the default version of Go from the GitHub Actions runner machine was used for generating the documentation content. A recent update of this default Go version from 1.17 to 1.20 (https://github.com/actions/runner-images/issues/7276) caused the generation process to fail:
- https://github.com/arduino/arduino-lint/actions/runs/4955302482/jobs/8864585754#step:6:9
- https://github.com/arduino/arduino-lint/actions/runs/4923773621/jobs/8795994762#step:4:87
```text
task: [go:rule-docs] …
```
=> Use project Go version for generating website content

.github/workflows/check-certificates.yml, .github/workflows/check-code-generation-task.yml, .github/workflows/check-general-formatting-task.yml, .github/workflows/check-go-dependencies-task.yml, .github/workflows/check-go-task.yml, .github/workflows/check-license.yml, .github/workflows/check-markdown-task.yml, .github/workflows/check-mkdocs-task.yml, .github/workflows/check-prettier-formatting-task.yml, .github/workflows/check-python-task.yml, .github/workflows/check-shell-task.yml, .github/workflows/check-workflows-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/release-go-task.yml, .github/workflows/spell-check-task.yml, .github/workflows/sync-labels.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml, .github/workflows/test-install.yml
[`GITHUB_TOKEN`](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) is an access token that is automatically generated and made accessible for use in GitHub Actions workflow runs. The global default permissions of this token for workflow runs in a trusted context (i.e., not triggered by a `pull_request` event from a fork) are set in the GitHub [enterprise](https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#enforcing-a-policy-for-workflow-permissions-in-your-enterprise)/[organization](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#setting-the-permissions-of-the-github …
=> Configure permissions of `GITHUB_TOKEN` in workflows

internal/project/project.go, internal/project/project_test.go
Having an `example` file in the library was causing the tool to panic, because it was being treated like a directory, but without checking if it was actually one.
The `example` file is just ignored now.
Close #751
The bug was discovered in https://github.com/arduino/library-registry/pull/4836
=> Fix example file causing panic

.github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml
A tool named **gon** is used to notarize the macOS release binaries. The [original gon tool](https://github.com/mitchellh/gon) is now nonfunctional due to its use of the **altool** tool, which is no longer permitted by Apple:
https://developer.apple.com/news/?id=y5mjxqmn
Fortunately [a fork of **gon**](https://github.com/Bearer/gon) was created and the migration from **altool** to **notarytool** completed in that fork. So the release workflows are hereby migrated to using the functional fork of **gon**.
=> Use Bearer/gon for macOS notarization of releases

.markdown-link-check.json, docs/installation.md
Increase link check timeout to 30s to allow enough time for the `nightly` redirector to work.
Temporarily removed macOS ARM64 version from the installation page, until the next release is made.
=> Increase markdown link check timeout to 30s

.github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/release-go-task.yml
GitHub Actions workflows are used to automatically generate beta tester and production builds of the project.
A separate build is generated for each of the target host types. This is done using a job matrix, which creates a parallel run of the workflow job for each target. The matrix defines variables that provide the data that is specific to each job.
The variable names used previously did not clearly communicate their nature:
- The variable for the task name was named "os"
- The variables for the build filename components used the term "artifact", which is ambiguous in this context where the term is otherwise used to refer to the completely unrelated workflow artifacts
These variable names made it very difficult for anyone not intimately familiar with the workings of the workflow to …
=> Refactor variables in release workflows

.github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml
In a previous revision of the release workflows (https://github.com/arduino/tooling-project-assets/pull/243), the updated checksums were determined by the macOS notarization job and then passed to the subsequent job via job outputs. That approach was changed during a later refactoring (https://github.com/arduino/tooling-project-assets/pull/277, https://github.com/arduino/tooling-project-assets/pull/326), but the code that declares the job outputs was not removed at that time.
The checksum job output declaration code is now unused (and unusable since the checksum determination and output definitions were removed) so it only makes the workflows more difficult to understand and maintain. For this reason, the vestigial code is hereby removed from the workflows.
=> Remove unused job outputs from release workflows

.github/dependabot.yml, .github/workflows/check-certificates.yml, .github/workflows/check-general-formatting-task.yml, .github/workflows/check-go-dependencies-task.yml, .github/workflows/check-go-task.yml, .github/workflows/check-license.yml, .github/workflows/check-markdown-task.yml, .github/workflows/check-mkdocs-task.yml, .github/workflows/check-prettier-formatting-task.yml, .github/workflows/check-python-task.yml, .github/workflows/check-shell-task.yml, .github/workflows/check-workflows-task.yml, .github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/spell-check-task.yml, .github/workflows/sync-labels.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml, .github/workflows/test-install.yml, .licensed.yml
The templates and documentation contain reference links to provide additional information to the users and maintainers.
The targets of some of these links have moved since the time they were added. Although the user could still reach the intended content via a redirect, it is best not to rely on redirects continuing to work indefinitely. So the URLs are hereby updated to point directly to the target content.
=> Update redirecting URLs in reference links

.github/workflows/check-certificates.yml, .github/workflows/check-code-generation-task.yml, .github/workflows/check-go-dependencies-task.yml, .github/workflows/check-go-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/sync-labels.yml, .github/workflows/test-go-task.yml
GitHub Actions provides the capability for workflow authors to use the capabilities of the GitHub Actions ToolKit package directly in the `run` keys of workflows via "[workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)". One such command is `set-output`, which allows data to be passed out of a workflow step as an output.
It has been determined that this command has potential to be a security risk in some applications. For this reason, GitHub has deprecated the command and a warning of this is shown in the workflow run summary page of any workflow using it:
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
=> Migrate workflows from deprecated `set-output` commands

.github/workflows/test-go-integration-task.yml
GitHub Actions provides the capability for workflow authors to use the capabilities of the GitHub Actions ToolKit package directly in the `run` keys of workflows via "[workflow commands](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions)". One such command is `set-output`, which allows data to be passed out of a workflow step as an output.
It has been determined that this command has potential to be a security risk in some applications. For this reason, GitHub has deprecated the command and a warning of this is shown in the workflow run summary page of any workflow using it:
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: …
=> Migrate workflow from deprecated `set-output` command

.github/workflows/check-go-task.yml, .github/workflows/check-license.yml, .github/workflows/check-mkdocs-task.yml, .github/workflows/check-prettier-formatting-task.yml, .github/workflows/check-python-task.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml
This repository contains several GitHub Actions workflows to facilitate the development and maintenance.
The workflows are typically configured to run whenever any relevant file in the repository is changed. However, the results of the workflow run are also dependent on the external environment it runs in, which include:
- The software running on the GitHub hosted GitHub Actions runner machines
- The GitHub Actions actions used by the workflow
- The dependencies that are installed by the workflow directly or via the GitHub Actions actions it uses
The workflows often do not fully pin to a specific version of given external tool. This was done in the interest on reducing the maintenance burden of keeping the systems up to date. However, it also means that a new release can cause the …
=> Add schedule triggers to workflows whenever possible

.github/workflows/check-shell-task.yml, Taskfile.yml
Background
----------
Previously, the approach taken shell script tasks was to recursively search the entire repository for shell scripts. There were several problems with that system:
---
The [`-regextype` flag](https://www.gnu.org/software/findutils/manual/html_node/find_html/Full-Name-Patterns.html#index-_002dregextype) used in the `find` commands of the `shell:check` and `shell:check-mode` tasks is not supported by [the BSD/macOS version of `find`](https://ss64.com/osx/find.html), meaning the tasks would fail if a contributor using a macOS machine tried to run them:
```text
find: -regextype: unknown primary or operator
```
---
The `shell:check` and `shell:check-mode` tasks only provided coverage for files with `.sh` and `.bash` file extensions, whereas the practice of omitting a file …
=> Target specific scripts in "Check Scripts" template

.github/workflows/check-license.yml
In cases where a project contains distinct components in subfolders, multiple license files might be present.
Previously the "Check License" workflow only supported checking the license file in the root of the repository. Support for validating an arbitrary number of license files with arbitrary locations, types, and filenames is added. A job matrix is used to provide this support in a manner that makes application-specific configuration of the workflow easy and without code duplication.
=> Add support to "Check License" for checking license files in multiple paths

.github/workflows/test-go-task.yml
For the sake of efficiency, the "Test Go" GitHub Actions workflow is [configured](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to run only when relevant files are modified. Since the workflow uploads code coverage data to [Codecov](https://about.codecov.io/), the Codecov configuration file is one of these files.
The standard filename for the Codecov configuration file is `codecov.yml`, and the workflow's path filter was configured for that filename. It turns out an alternative filename is also recognized: `.codecov.yml`. Two subfolders are also supported in addition to the root of the repository as locations for the configuration file. …
=> Add support to "Test Go" workflow for alternative Codecov configuration paths

.github/workflows/check-go-task.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml
It is often necessary to escape the newline for continuation when breaking shell commands into multiple lines for readability. However, if a line break occurs in a shell command in an unterminated command, the continuation is implicit.
The escaping in these shell commands was unnecessary and only made them a bit more cryptic, since the brackets already clearly indicate the structure
=> Remove unnecessary line continuation escaping from workflows

.github/workflows/check-shell-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml, Taskfile.yml
120 columns is the recommended line length for YAML code in Arduino tooling projects. The yamllint tool used by the "Check YAML" template produces a warning when a line exceeds this length.
This is not a hard limit and in some cases it is either impossible or not beneficial to make lines less than 120 in length so some violations of the guideline are unavoidable. However, a survey of the YAML files in the repository revealed some opportunities for improving the code by reducing the lengths.
=> Reduce line length to <=120 in YAML files where feasible

.codespellrc, .ecrc, .markdownlintignore, .prettierignore
In order to avoid spurious results and to improve efficiency, automatically generated or externally maintained files should be excluded from automated processes. The coverage of ignore configurations is hereby expanded to cover more paths containing such files.
=> Expand ignored path configurations

.github/workflows/publish-go-tester-task.yml
The "Publish Tester Build" workflow is triggered by the [`push` event](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push). This event occurs on tag pushes in addition to commit pushes.
On a tag push, there is an ambiguity in how the build should be identified, since the revision has two Git refs:
- The commit hash
- The tag name
The build system intentionally uses the tag name ref to name the build archives, but the workflow's checksum file generation code expects the files to be named using the commit hash ref. This resulted in a spurious failure of the "Create checksum file" step of the `checksums` job with an error of the form:
```
sha256sum: 'arduino-lint_test-052e9032aa396ac0a4c356eaf7c8dc5ca3f4ad4b-git-snapshot*': …
```
=> Don't run "Publish Tester Build" workflow on tag push

.ecrc
The `Exclude` key of the `.ecrc` configuration file specifies regular expressions of paths that should be ignored by the editorconfig-checker tool. Previously, the regular expression only accommodated the POSIX-compliant path separator, meaning the path was not excluded as intended when used on a Windows system (even when ran from a Bash shell).
=> Add Windows path support to editorconfig-checker exclude regex

.github/workflows/check-certificates.yml
The digital certificates used for code signing are often stored in an archive file of the [PKCS #12](https://en.wikipedia.org/wiki/PKCS_12) format, which allows multiple objects to be bundled in a single file.
However, it also might occur that a single certificate is stored in [X.509](https://en.wikipedia.org/wiki/X.509) format.
Previously, the "Check Certificates" workflow only supported certificates in a PKCS #12 archive. Support is hereby added to the workflow for validation of X.509 certificates in addition to PKCS #12.
=> Add support for non-bundled X.509 certificates to "Check Certificates" workflow

.ecrc, .github/workflows/check-markdown-task.yml, .gitignore, .markdownlintignore, .prettierignore, Taskfile.yml, docs/CONTRIBUTING.md, package-lock.json, package.json
The project uses several tools for development and validation of Markdown files. Previously, the version of the tools used was not controlled. This was problematic because:
- A different version of the tool may be used on the contributor's machine than on the CI runner, resulting in confusing failures.
- The project is immediately subject to disruption or breakage resulting from a release of the tool.
The new approach is to specify the version of the tools via the standard npm metadata files (package.json + package-lock.json), providing the following benefits:
- Enables automated updates via Dependabot PRs
- Enables automated vulnerability alerts
=> Use npm to manage Markdown tool dependencies

Taskfile.yml
The `markdown:check-links` task uses the [**markdown-link-check**](https://github.com/tcort/markdown-link-check). This tool [does not have a capability for discovering Markdown files](https://github.com/tcort/markdown-link-check/issues/40) so it is necessary to use the [`find`](https://www.gnu.org/software/findutils/manual/html_node/find_html/Invoking-find.html) command to discover the files, then pass their paths to the **markdown-link-check** tool.
Since it is managed as a project dependency using [**npm**](https://www.npmjs.com/), the **markdown-link-check** tool is invoked using [`npx`](https://docs.npmjs.com/cli/commands/npx). Since the `find` command must be ran in combination with **markdown-link-check**, it is necessary to use the `--call` flag of `npx`. Even though Windows …
=> Avoid platform-specific code in `markdown:check-links` task

.github/workflows/check-prettier-formatting-task.yml, Taskfile.yml, package-lock.json, package.json
The project uses the Prettier tool to format various file types. Previously, the version of the tool used was not controlled. This was problematic because:
- A different version of the tool may be used on the contributor's machine than on the CI runner, resulting in confusing failures.
- The project is immediately subject to disruption or breakage resulting from a release of the tool.
The new approach is to specify the version of the tools via the standard npm metadata files (package.json + package-lock.json), providing the following benefits:
- Enables automated updates via Dependabot PRs
- Enables automated vulnerability alerts
=> Use npm to manage Prettier tool dependency

.github/workflows/check-npm-task.yml, README.md, Taskfile.yml
A task and GitHub Actions workflow are provided here for checking the project's npm package manager configuration.
On every push and pull request that affects relevant files, and periodically:
- Validate package.json against its JSON schema.
- Check for forgotten package-lock.json syncs.
=> Add infrastructure to check for problems with npm configuration files

.github/dependabot.yml
Dependabot will periodically check all npm package dependencies of the project. If any are found to be outdated, it will submit a pull request to update them.
=> Configure Dependabot to check for outdated npm package dependencies

.github/workflows/check-markdown-task.yml, .github/workflows/check-npm-task.yml, .github/workflows/check-prettier-formatting-task.yml, docs/CONTRIBUTING.md, package-lock.json, package.json
The "actions/setup-node" GitHub Actions action is used to set up Node.js in the GitHub Actions runner machine.
The action supports obtaining the Node.js version to set up from the `engines.node` property of the package.json file.
This allows us to define the standardized version of Node.js for use by project contributors in a single place rather than having to maintain multiple instances of that data.
=> Use engines.node as source of version data for "actions/setup-node" action

.github/workflows/check-workflows-task.yml, Taskfile.yml, package-lock.json, package.json
The project uses the ajv-cli tool to validate GitHub Actions workflows against the JSON schema. Previously, the version of the tool used was not controlled. This was problematic because:
- A different version of the tool may be used on the contributor's machine than on the CI runner, resulting in confusing failures.
- The project is immediately subject to disruption or breakage resulting from a release of the tool.
The new approach is to specify the version of the tools via the standard npm metadata files (package.json + package-lock.json), providing the following benefits:
- Enables automated updates via Dependabot PRs
- Enables automated vulnerability alerts
=> Use npm to manage "Check Workflows" tool dependencies

Taskfile.yml
The tasks for facilitating development and validation of shell scripts were recently adjusted to target specific scripts (https://github.com/arduino/arduino-lint/pull/773). After that change, it is necessary to specify the path to the script in the task call.
For the convenience of the contributor, the taskfile contains some "umbrella" tasks that call all of the tasks of a given type. These call the shell-related tasks. Those calls were not updated at the time the shell tasks were changed to a targeted approach so previously they were not functional.
=> Configure script path in shell-related task calls in umbrella tasks

Taskfile.yml
The `general:cache-dep-licenses` task is used to generate metadata about the licenses of the project's dependencies.
When using some dependency management systems, it is necessary to run an operation via the dependency management tool prior to generating the metadata. A task call was added to the `general:cache-dep-licenses` task in order to allow it to be used with such project types. It happens that such a preparatory operation is not necessary with the Go modules dependency management system used by this project, so the preparation task is left empty.
=> Add support for dependencies preparation to `general:cache-dep-licenses` task

Taskfile.yml
The Task task runner tool uses an integrated Bash shell interpreter to allow the use of standard POSIX/Bash syntax and built-in utilities while providing cross-platform support for users who have made the poor choice of the non-standard Windows cmd or PowerShell shells.
While this is a nice feature of Task, distinguishing it from other alternatives, it is still often necessary to use non-built-in utilities. So use of a Bash shell is a requirement to run our tasks even the developers using Windows.
Although high quality Bash shells for Windows such as the Git Bash included as part of the Git for Windows installation generally provide a seamless experience, there is the occasional "gotcha".
Relative paths work the same for POSIX and Windows, but absolute POSIX format paths may not. These …
=> Convert absolute paths used in `ci:validate` task to Windows format

.github/workflows/sync-labels-npm.yml, README.md, package-lock.json, package.json
Several tools are used by the "Sync Labels" workflow. The new approach is to specify the version of the tools via the standard npm metadata files (package.json + package-lock.json), providing the following benefits:
- Enables automated updates via Dependabot PRs
- Enables automated vulnerability alerts
=> Migrate to npm-managed GitHub label sync infrastructure

.github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml
The "Deploy Website" workflow invokes the following chain of tasks:
1. `docs:generate`
2. `general:format-prettier`
This makes the Prettier tool a dependency of the workflow, which in turn introduces a dependency on npm, and thus on Node.js.
Previously, the workflow didn't contain a step to run the "actions/setup-node" action, so it used whichever version of npm happened to be installed in the runner machine, which happens to be 18.x currently. Now that the use of the project's standard Node.js version 20.x is enforced, this caused the workflow runs to fail spuriously:
```
task: [npm:install-deps] npm install
npm error code EBADENGINE
npm error engine Unsupported engine
npm error engine Not compatible with your version of node/npm: undefined
npm error notsup Not compatible with your …
```
=> Install standard version of Node.js in "Deploy Website" workflow

.gitattributes, .github/workflows/check-mkdocs-task.yml, .github/workflows/check-python-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/spell-check-task.yml, .github/workflows/test-go-integration-task.yml, poetry.lock, pyproject.toml
Python and Python-based tools are used in the development and maintenance of the project. A standardized version of Python is used for these operations.
Poetry is used for Python package dependencies management. Poetry installs dependencies into a virtual environment. For this reason, the Poetry configuration includes a Python version number, which must match the correct version of Python for the project. This configuration is stored in the [`pyproject.toml` file](https://python-poetry.org/docs/pyproject/).
Python is installed in the GitHub Actions runner environments using the **actions/setup-python** action, which also must be configured to install the correct version of Python. Previously the version number for use by the actions/setup-python action was defined in each workflow. This …
=> Use `pyproject.toml` as Python version source

docs/CONTRIBUTING.md
Python and Python-based tools are used in the development and maintenance of the project. A standardized version of Python is used for these operations. The contributor will need to have this version installed if they want to perform the dependent operations. For this reason, the dependency on Python and the standardized version is documented in the contributor guide.
Poetry is used for Python package dependencies management. Poetry installs dependencies into a virtual environment. For this reason, the Poetry configuration includes a Python version number, which must match the correct version of Python for the project. This configuration is stored in the `pyproject.toml` file. This is also used as the source of Python versioning information by all other parts of the infrastructure …
=> Reference canonical Python version info source in contributor guide

.github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml
GitHub Workflows are used to automatically generate and publish production and nightly releases of the project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
GitHub Actions workflow artifacts are used to transfer the generated files between sequential jobs in the workflow. The **actions/upload-artifact** and **actions/download-artifact** actions are used for this purpose.
The workflow artifact handling had to be reworked recently in order to handle a breaking change in the 4.0.0 release of the **actions/upload-artifact** action (https://github.com/arduino/arduino-lint/pull/662 / https://github.com/arduino/arduino-lint/commit/3289cb81a8d88bce29a86af99191711005885456). Previously, a …
=> Fix collision between macOS workflow artifacts in release workflows

.github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml
GitHub Workflows are used to automatically generate and publish production and nightly releases of the project. This is done for a range of host architectures, including macOS. The macOS builds are then put through a notarization process in a dedicated workflow job.
GitHub Actions workflow artifacts are used to transfer the generated files between sequential jobs in the workflow. The builds are transferred between jobs by GitHub Actions workflow artifacts, one for each host architecture.
Previously, the "notarize-macos" job matrix that performs the notarization unnecessarily downloaded all the build artifacts, even though each job only requires the relevant macOS artifact. This is inefficient.
The better approach is to configure the "notarize-macos" jobs to only download the artifact they …
=> Only download required artifact in notarization job of release workflows

.github/workflows/check-code-generation-task.yml, .github/workflows/check-go-dependencies-task.yml, .github/workflows/check-go-task.yml, .github/workflows/check-markdown-task.yml, .github/workflows/check-mkdocs-task.yml, .github/workflows/deploy-cobra-mkdocs-versioned-poetry.yml, .github/workflows/test-go-integration-task.yml, .github/workflows/test-go-task.yml, DistTasks.yml, docsgen/go.mod, go.mod, ruledocsgen/go.mod
Go is used in the development and maintenance of the project. A standardized version of Go is used for all operations.
This version is defined in the [`go` directive](https://go.dev/ref/mod#go-mod-file-go) of the `go.mod` metadata file.
Go is installed in the GitHub Actions runner environments using the **actions/setup-go** action, which also must be configured to install the correct version of Go. Previously the version number for use by the **actions/setup-go** action was defined in each workflow. This meant that we had multiple copies of the Go version information, all of which had to be kept in sync.
Fortunately, support for using `go.mod` as the source of version information for the **actions/setup-go** action was recently added: …
=> Use `go.mod` as source of Go version number for workflows

.github/workflows/publish-go-nightly-task.yml, .github/workflows/release-go-task.yml
For security reasons long lived credentials are not considered secure.
To overcome this issue we can configure Github Workflows to use AWS OpenID Connect instead:
For further details: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
Tested:
=> github: Use IAM Roles to push files on AWS S3

docs/installation.md
Added back the macOS ARM64 link because a new release was published, reverting the changes introduced in #765.
=> Add back link to macOS ARM release

.github/workflows/check-go-dependencies-task.yml
This GitHub Actions action is used by the "Check Go Dependencies" workflow to install the "Licensed" tool in the runner workspace. At the time the workflow was developed, the action was owned by GitHub user `jonabc`, and so the action was referenced as `jonabc/setup-licensed` in the workflow.
Since that time, the action was transferred to the `github` GitHub organization:
https://github.com/github/setup-licensed
Making things more confusing is the fact that there is now a development fork of the `github/setup-licensed` repository under GitHub user `jonabc`'s account, meaning that the redirect GitHub provides from the old to the new repository after a transfer does not exist for this action. This resulted in the workflow referencing an outdated and unmaintained copy of the action.
The …
=> Use canonical github/setup-licensed action in "Check Go Dependencies" workflow

.github/workflows/check-go-dependencies-task.yml
The version of the [**Licensed**](https://github.com/github/licensed) tool for use in the GitHub Actions workflow is defined via the **github/setup-licensed** action's `version` input.
Previously the action was configured to install version 3.x of the action. That version is significantly outdated. The workflow is hereby updated to use the latest version of **Licensed**.
=> Update Licensed version in "Check Go Dependencies" workflow

.licensed.yml, .licenses/arduino-lint/go/github.com/klauspost/compress.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/fse.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/huff0.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/internal/cpuinfo.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/internal/snapref.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/zstd.dep.yml, .licenses/arduino-lint/go/github.com/klauspost/compress/zstd/internal/xxhash.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/fse.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/huff0.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/internal/cpuinfo.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/internal/snapref.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/zstd.dep.yml, .licenses/docsgen/go/github.com/klauspost/compress/zstd/internal/xxhash.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress/fse.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress/huff0.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress/internal/cpuinfo.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress/internal/snapref.dep.yml, .licenses/ruledocsgen/go/github.com/klauspost/compress/zstd.dep.yml
The [**Licensed**](https://github.com/github/licensed) tool is used to check for incompatible licenses in the project dependencies. The tool can be configured to ignore incompatible license types for specific dependencies. This is done by adding an entry for the dependency to the `reviewed` entry in the **Licensed** configuration file.
Such exceptions should be added only when the project maintainer has determined the following things to be true:
- dependency license is not one of the standard compatible types (as defined by the `allowed` mapping in the config)
- dependency license is compatible with the licensing of the project (e.g., dependency uses a non-standard but compatible license)
**Licensed** uses the [**licensee**](https://github.com/licensee/licensee) tool to automatically …
=> Remove inappropriate dependency license exception entries from Licensed configuration

.github/workflows/check-go-dependencies-task.yml
The [**github/setup-licensed**](https://github.com/github/setup-licensed) action is used by the dependencies license check workflow to install the [**Licensed**](https://github.com/github/licensed) tool in the runner machine.
Previously the `v1` [major version ref](https://docs.github.com/actions/sharing-automations/creating-actions/about-custom-actions#good-practices-for-release-management) of the action was specified in the workflow. This approach is used in order to allow the workflow to automatically always use the latest minor version of the action, only requiring the project maintainers to perform a bump of the action after each major version release.
In a competently maintained action project, the major version ref will be updated after each release within that major version series …
=> Use latest version of "github/setup-licensed" action

Taskfile.yml
The project infrastructure includes a check for commonly misspelled words in the project files.
Although the system is designed to reduce the incidence of false positives, they are still relatively common. For this reason, it is important to clearly communicate to the contributor how such false positives can be resolved. This can be accomplished effectively by printing instructions when the spell check fails.
In order to avoid excessive verbosity of the output (note that the failure could just as well be a true positive), the description of the procedure is maintained in the asset documentation and the output message simply provides the URL of that documentation.
=> Print instructions for false positive resolution when spell check fails

.github/workflows/publish-go-nightly-task.yml, .github/workflows/publish-go-tester-task.yml, .github/workflows/release-go-task.yml
The `docker.elastic.co/beats-dev/golang-crossbuild:1.24.0-darwin-arm64-debian10` container is used for the release builds for the macOS Apple Silicon host. This container will only run on hosts of the linux/arm64 architecture.
The GitHub Actions runner machine previously used to perform the release builds is of the linux/amd64 architecture and so is not compatible with the container. This caused the release builds to fail:
```text
Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.24.0-darwin-arm64-debian10
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /crossbuild: exec format error
task: Failed to run task "dist:macOS_ARM64": exit status 255 …
```
=> Fix macOS Apple Silicon release builds

Taskfile.yml
This task updates all the project's Python package dependencies to the latest version.
Performing bulk updates is not a good practice, since it is non-atomic and thus makes it difficult to bisect regressions caused by the update. In addition, it is not necessary since dependencies are now updated using Dependabot.
For these reasons, the task is harmful and superfluous.
=> Remove `poetry:update-deps` task
